### ISSUE TITLE
CoupledMCMC execution on clusters

### ISSUE THREAD

**Issue by dreyes17** [nicfel/CoupledMCMC#18]
Hello,

I know that Beast2 supports Beagle and as Mrbayes this should be able to run in different nodes of a cluster. This package is prepared  to run for example 32 chains in 2 nodes of 16 cpus?

**Comment by rbouckaert** [comment]
With 'nodes' you mean two different computers or two CPUs on the same computer? For the latter, it should just work out of the box. However, it is not possible to run a single CoupledMCMC job over multiple computers at the moment.

**Comment by dreyes17** [comment]
Yes I meant on different computers. Thank you very much for you answer.
